<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class WC_Superadmin_Client_Settings {

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'add_settings_page' ) );
		add_action( 'admin_init', array( $this, 'register_settings' ) );
		add_action( 'admin_init', array( $this, 'maybe_register_with_hub' ) );
	}

	public function add_settings_page() {
		add_options_page(
			'WC Superadmin Client',
			'Superadmin Client',
			'manage_options',
			'wc-superadmin-client',
			array( $this, 'render_settings_page' )
		);
	}

	public function register_settings() {
		register_setting( 'wc_superadmin_client_options', 'wc_superadmin_public_key' );
		register_setting( 'wc_superadmin_client_options', 'wc_superadmin_hub_url', array(
			'default'           => 'https://admindemo.kimbr.no',
			'sanitize_callback' => 'esc_url_raw',
		) );
	}

	/**
	 * Fires after our settings page is saved (checks for the settings-updated flag).
	 * This is more reliable than updated_option which doesn't fire on first save.
	 */
	public function maybe_register_with_hub() {
		// Only run on our settings page after a successful save
		if (
			! isset( $_GET['page'] ) || $_GET['page'] !== 'wc-superadmin-client' ||
			! isset( $_GET['settings-updated'] ) || $_GET['settings-updated'] !== 'true'
		) {
			return;
		}

		$hub_url = get_option( 'wc_superadmin_hub_url', 'https://admindemo.kimbr.no' );

		if ( empty( $hub_url ) ) {
			return;
		}

		$registration_endpoint = trailingslashit( $hub_url ) . 'wp-json/wc-superadmin-hub/v1/register';

		$response = wp_remote_post( $registration_endpoint, array(
			'timeout' => 10,
			'body'    => array(
				'client_url' => site_url(),
			),
		) );

		if ( is_wp_error( $response ) ) {
			update_option( 'wc_superadmin_registration_status', 'error: ' . $response->get_error_message() );
		} else {
			$body = json_decode( wp_remote_retrieve_body( $response ), true );
			if ( ! empty( $body['success'] ) ) {
				update_option( 'wc_superadmin_registration_status', 'success' );
			} else {
				update_option( 'wc_superadmin_registration_status', 'error: unexpected response from hub' );
			}
		}
	}

	public function render_settings_page() {
		$registration_status = get_option( 'wc_superadmin_registration_status', '' );
		?>
		<div class="wrap">
			<h1>WC Superadmin Client Settings</h1>

			<?php if ( $registration_status === 'success' ) : ?>
				<div class="notice notice-success is-dismissible">
					<p>✅ <strong>Successfully registered</strong> with the Central Hub!</p>
				</div>
			<?php elseif ( ! empty( $registration_status ) && strpos( $registration_status, 'error' ) === 0 ) : ?>
				<div class="notice notice-error is-dismissible">
					<p>❌ <strong>Hub registration failed:</strong> <?php echo esc_html( $registration_status ); ?></p>
					<p>Please check the Hub URL and ensure the Hub plugin is active on that site.</p>
				</div>
			<?php endif; ?>

			<form method="post" action="options.php">
				<?php settings_fields( 'wc_superadmin_client_options' ); ?>
				<table class="form-table">
					<tr valign="top">
						<th scope="row">Central Hub URL</th>
						<td>
							<input
								type="url"
								name="wc_superadmin_hub_url"
								value="<?php echo esc_attr( get_option( 'wc_superadmin_hub_url', 'https://admindemo.kimbr.no' ) ); ?>"
								class="regular-text"
								placeholder="https://admindemo.kimbr.no"
							/>
							<p class="description">The URL of your Central Hub WordPress site. This site will automatically register itself with the hub when you save.</p>
						</td>
					</tr>
					<tr valign="top">
						<th scope="row">Hub Public Key</th>
						<td>
							<textarea name="wc_superadmin_public_key" rows="10" cols="50" class="large-text code"><?php echo esc_textarea( get_option( 'wc_superadmin_public_key' ) ); ?></textarea>
							<p class="description">Paste the RSA Public Key generated by your Central Hub here.</p>
						</td>
					</tr>
				</table>
				<?php submit_button( 'Save & Register with Hub' ); ?>
			</form>
		</div>
		<?php
	}
}

new WC_Superadmin_Client_Settings();
